### ISSUE TITLE
Inconsistencies to the monero PR

### ISSUE THREAD

**Issue by tsusanka** [ph4r05/monero-trezor-doc#3]
Just to track inconsistencies to the code introduced in https://github.com/trezor/trezor-core/pull/293 in case we decide to level it out:

- [x] we are currently not using the private data reconstruction on page 14 right?
- [x] page 22 - 2a) we are now offloading always, right?
- [x] page 22 - 2d) only in the case of simple RCT right?
- [x] on page 22 - the step 5 as in code is missing. Maybe we could add it so it's corresponding to the code? even with one line, just so the numbers relate to the code
- [x] 4.2 protocol selection, we are now always using the multi-step right?

I'm not saying we need to do those nit-picks, just to track what I believe is different.

------------

- [x] page 22 - step 6b is actually done in the following step
- [x] full_message_hash vs final_message_hash

**Comment by ph4r05** [comment]
I think this is now all sorted out.

**Comment by tsusanka** [comment]
Confirmed, thanks!
