### ISSUE TITLE
Overleaf link broken

### ISSUE THREAD

**Issue by pocin** [ph4r05/monero-trezor-doc#4]
Hi, the overleaf link is broken (requires project migration to v2) and I can't seem to build it using `make_pdf[html].sh` because `monero.md` file is missing.
I ended up copying the source to my own overleaf project which works, but... :-)

**Comment by ph4r05** [comment]
The project just needed migration to overleaf2. Now works.
`*.md` is an old artifact, it won't be supported anymore.

Thx for info.
